// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6BMnup_BFbsaM-0_0hqk0CQU87idLbno',
    appId: '1:16779298545:web:4c663f52acdbdff7608b50',
    messagingSenderId: '16779298545',
    projectId: 'travvite',
    authDomain: 'travvite.firebaseapp.com',
    storageBucket: 'travvite.firebasestorage.app',
    measurementId: 'G-VMSYESS5P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQaMlpXevda-xZit0BVJaxTwtKd6rRTZ0',
    appId: '1:16779298545:android:8e0b07eccec8df83608b50',
    messagingSenderId: '16779298545',
    projectId: 'travvite',
    storageBucket: 'travvite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrM9Fo91fuXdZelmJ9o-3_dYIZ9UzgKo8',
    appId: '1:16779298545:ios:eba39336293980ab608b50',
    messagingSenderId: '16779298545',
    projectId: 'travvite',
    storageBucket: 'travvite.firebasestorage.app',
    iosBundleId: 'com.kelthame.travvite.travvite1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrM9Fo91fuXdZelmJ9o-3_dYIZ9UzgKo8',
    appId: '1:16779298545:ios:eba39336293980ab608b50',
    messagingSenderId: '16779298545',
    projectId: 'travvite',
    storageBucket: 'travvite.firebasestorage.app',
    iosBundleId: 'com.kelthame.travvite.travvite1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6BMnup_BFbsaM-0_0hqk0CQU87idLbno',
    appId: '1:16779298545:web:087d6852ec51766c608b50',
    messagingSenderId: '16779298545',
    projectId: 'travvite',
    authDomain: 'travvite.firebaseapp.com',
    storageBucket: 'travvite.firebasestorage.app',
    measurementId: 'G-XXJ1SJ1VGH',
  );
}
